package com.zjc.dao.model;

import java.io.Serializable;

public class SysUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.id
     *
     * @mbg.generated Wed Apr 22 14:58:47 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.username
     *
     * @mbg.generated Wed Apr 22 14:58:47 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.password
     *
     * @mbg.generated Wed Apr 22 14:58:47 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.nickname
     *
     * @mbg.generated Wed Apr 22 14:58:47 CST 2020
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.roles
     *
     * @mbg.generated Wed Apr 22 14:58:47 CST 2020
     */
    private String roles;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.enabled
     *
     * @mbg.generated Wed Apr 22 14:58:47 CST 2020
     */
    private Boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.accountNonExpired
     *
     * @mbg.generated Wed Apr 22 14:58:47 CST 2020
     */
    private Boolean accountnonexpired;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.credentialsNonExpired
     *
     * @mbg.generated Wed Apr 22 14:58:47 CST 2020
     */
    private Boolean credentialsnonexpired;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.accountNonLocked
     *
     * @mbg.generated Wed Apr 22 14:58:47 CST 2020
     */
    private Boolean accountnonlocked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table USER
     *
     * @mbg.generated Wed Apr 22 14:58:47 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.id
     *
     * @return the value of USER.id
     *
     * @mbg.generated Wed Apr 22 14:58:47 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.id
     *
     * @param id the value for USER.id
     *
     * @mbg.generated Wed Apr 22 14:58:47 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.username
     *
     * @return the value of USER.username
     *
     * @mbg.generated Wed Apr 22 14:58:47 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.username
     *
     * @param username the value for USER.username
     *
     * @mbg.generated Wed Apr 22 14:58:47 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.password
     *
     * @return the value of USER.password
     *
     * @mbg.generated Wed Apr 22 14:58:47 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.password
     *
     * @param password the value for USER.password
     *
     * @mbg.generated Wed Apr 22 14:58:47 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.nickname
     *
     * @return the value of USER.nickname
     *
     * @mbg.generated Wed Apr 22 14:58:47 CST 2020
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.nickname
     *
     * @param nickname the value for USER.nickname
     *
     * @mbg.generated Wed Apr 22 14:58:47 CST 2020
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.roles
     *
     * @return the value of USER.roles
     *
     * @mbg.generated Wed Apr 22 14:58:47 CST 2020
     */
    public String getRoles() {
        return roles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.roles
     *
     * @param roles the value for USER.roles
     *
     * @mbg.generated Wed Apr 22 14:58:47 CST 2020
     */
    public void setRoles(String roles) {
        this.roles = roles == null ? null : roles.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.enabled
     *
     * @return the value of USER.enabled
     *
     * @mbg.generated Wed Apr 22 14:58:47 CST 2020
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.enabled
     *
     * @param enabled the value for USER.enabled
     *
     * @mbg.generated Wed Apr 22 14:58:47 CST 2020
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.accountNonExpired
     *
     * @return the value of USER.accountNonExpired
     *
     * @mbg.generated Wed Apr 22 14:58:47 CST 2020
     */
    public Boolean getAccountnonexpired() {
        return accountnonexpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.accountNonExpired
     *
     * @param accountnonexpired the value for USER.accountNonExpired
     *
     * @mbg.generated Wed Apr 22 14:58:47 CST 2020
     */
    public void setAccountnonexpired(Boolean accountnonexpired) {
        this.accountnonexpired = accountnonexpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.credentialsNonExpired
     *
     * @return the value of USER.credentialsNonExpired
     *
     * @mbg.generated Wed Apr 22 14:58:47 CST 2020
     */
    public Boolean getCredentialsnonexpired() {
        return credentialsnonexpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.credentialsNonExpired
     *
     * @param credentialsnonexpired the value for USER.credentialsNonExpired
     *
     * @mbg.generated Wed Apr 22 14:58:47 CST 2020
     */
    public void setCredentialsnonexpired(Boolean credentialsnonexpired) {
        this.credentialsnonexpired = credentialsnonexpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.accountNonLocked
     *
     * @return the value of USER.accountNonLocked
     *
     * @mbg.generated Wed Apr 22 14:58:47 CST 2020
     */
    public Boolean getAccountnonlocked() {
        return accountnonlocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.accountNonLocked
     *
     * @param accountnonlocked the value for USER.accountNonLocked
     *
     * @mbg.generated Wed Apr 22 14:58:47 CST 2020
     */
    public void setAccountnonlocked(Boolean accountnonlocked) {
        this.accountnonlocked = accountnonlocked;
    }
}