server:
  port: 8899

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  redis:
    database: 6
    timeout: 3000
    # Redis服务器地址
    host: 192.168.204.66
#    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: redis
#    password: 123456
    # 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0


logging:
  level:
    root: info

